---
version: "3"

vars:
  MODULE_PATH: modules/subnet

tasks:
  readme:
    run: once
    desc: Generate Readme
    silent: true
    cmds:
      - >-
        gomplate --file {{.README_TEMPLATE}} --out {{.MODULE_PATH}}/README.md --datasource config={{.MODULE_PATH}}/README.yaml --datasource includes={{.README_INCLUDES}}

  test:
    desc: test module
    silent: true
    cmds:
      - >-
        go test -race -v ./{{.MODULE_PATH}}/... -coverprofile cover.out -timeout 60m
